# Generated by Django 3.1 on 2021-06-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish_app', '0003_dayofweek_menuforweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayofweek',
            name='slug',
            field=models.SlugField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
